### ISSUE TITLE
uninitialized constant Fluent::TextParser::Parser

### ISSUE THREAD

**Issue by eugeneaik** [fluent-plugins-nursery/fluent-plugin-kv-parser#4]
Hi,
I have an issue with plugin:
2017-05-31 15:33:13 +0300 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2017-05-31 15:33:13 +0300 [info]: starting fluentd-0.14.16 pid=39741
2017-05-31 15:33:13 +0300 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/sbin/td-agent", "--log", "/var/log/td-agent/td-agent.log", "--daemon", "/var/run/td-agent/td-agent.pid", "--under-supervisor"]
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-plugin-elasticsearch' version '1.9.5'
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-plugin-grok-parser' version '2.1.3'
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-plugin-kafka' version '0.5.5'
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-plugin-kv-parser' version '0.0.1'
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-plugin-mongo' version '0.8.0'
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-plugin-s3' version '0.8.2'
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-plugin-td' version '0.10.29'
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2017-05-31 15:33:14 +0300 [info]: gem 'fluent-plugin-webhdfs' version '0.4.2'
2017-05-31 15:33:14 +0300 [info]: gem 'fluentd' version '0.14.16'
2017-05-31 15:33:14 +0300 [info]: gem 'fluentd' version '0.12.35'
2017-05-31 15:33:14 +0300 [info]: adding match in @WG pattern="watchguard.**" type="stdout"
2017-05-31 15:33:14 +0300 [info]: adding source type="udp"
2017-05-31 15:33:14 +0300 [error]: #0 unexpected error error_class=NameError error="uninitialized constant Fluent::TextParser::Parser"
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kv-parser-0.0.1/lib/fluent/plugin/parser_kv.rb:3:in `<class:TextParser>'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kv-parser-0.0.1/lib/fluent/plugin/parser_kv.rb:2:in `<module:Fluent>'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kv-parser-0.0.1/lib/fluent/plugin/parser_kv.rb:1:in `<top (required)>'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/registry.rb:102:in `block in search'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/registry.rb:99:in `each'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/registry.rb:99:in `search'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/registry.rb:44:in `lookup'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/plugin.rb:146:in `new_impl'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/plugin.rb:123:in `new_parser'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/plugin_helper/parser.rb:89:in `block in configure'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/plugin_helper/parser.rb:85:in `each'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/plugin_helper/parser.rb:85:in `configure'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/plugin_helper/server.rb:306:in `configure'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/plugin/in_udp.rb:46:in `configure'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/plugin.rb:164:in `configure'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/root_agent.rb:270:in `add_source'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/root_agent.rb:119:in `block in configure'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/root_agent.rb:115:in `each'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/root_agent.rb:115:in `configure'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/engine.rb:127:in `configure'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/engine.rb:92:in `run_configure'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/supervisor.rb:733:in `run_configure'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/supervisor.rb:502:in `block in run_worker'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/supervisor.rb:661:in `call'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/supervisor.rb:661:in `main_process'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/supervisor.rb:498:in `run_worker'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.16/bin/fluentd:5:in `<top (required)>'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2017-05-31 15:33:14 +0300 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2017-05-31 15:33:14 +0300 [error]: #0 /usr/sbin/td-agent:7:in `load'
  2017-05-31 15:33:14 +0300 [error]: #0 /usr/sbin/td-agent:7:in `<main>'

here is my config:

 cat /etc/td-agent/td-agent.conf
<source>
  @type udp
  port 12515
  format kv
  tag watchguard
  @label @WG
</source>

<label @WG>
        <match watchguard.**>
                @type stdout
        </match>

</label>

**Comment by kenhys** [comment]
fluentd 0.14.6 and fluent-plugin-kv-parser' version '0.0.1' may be used with incompatible plugin API.
So it may be bettet to use latest fluent-plugin-kv-parser 1.0.0.

**Comment by kenhys** [comment]
I'll close this issue because updating fluent-plugin-kv-parser  gem resolves it.
